version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: coffee-postgres
    environment:
      POSTGRES_DB: coffee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "54329:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    command: postgres -c listen_addresses='*'

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: coffee-backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/coffee_db
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-change-in-production}
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: coffee-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: 